/*
 * JMRTD - A Java API for accessing machine readable travel documents.
 *
 * Copyright (C) 2006 - 2018  The JMRTD team
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 *
 * $Id: PACEInfo.java 1850 2021-05-21 06:25:03Z martijno $
 */
/*
 * Modified work Copyright (C) 2026 Alessandro Giaquinto
 * Kotlin port of JMRTD
 *
 * Licensed under LGPL 3.0
 */
package kmrtd.lds

import kmrtd.Util
import org.bouncycastle.asn1.*
import org.bouncycastle.jce.ECNamedCurveTable
import java.math.BigInteger
import java.security.spec.AlgorithmParameterSpec
import java.security.spec.ECParameterSpec
import java.util.*
import java.util.logging.Logger
import javax.crypto.spec.DHParameterSpec

/**
 * PACE Info object as per SAC TR 1.01, November 11, 2010.
 * 
 * @author The JMRTD team (info@jmrtd.org)
 * 
 * @version $Revision: 1850 $
 * 
 * @since 0.5.0
 */
class PACEInfo(oid: String?, version: Int, parameterId: BigInteger?) : SecurityInfo() {
    /**
     * A DH parameter specification which also keeps track of
     * the prime order of the subgroup generated by the generator.
     * 
     * @author The JMRTD team (info@jmrtd.org)
     * 
     * @version $Revision: 1850 $
     */
    class DHCParameterSpec
    /**
     * Creates a parameter specification.
     * 
     * @param p the prime
     * @param g the generator
     * @param q the prime order of subgroup generated by `g`
     */(
        p: BigInteger?, g: BigInteger?,
        /**
         * Returns the prime order of subgroup generated by `g`.
         * 
         * @return the prime order of subgroup generated by `g`
         */
        val q: BigInteger?
    ) : DHParameterSpec(p, g)

    /** Generic mapping and Integrated mapping and CAM mapping.  */
    enum class MappingType {
        /** Generic Mapping.  */
        GM,

        /** Integrated Mapping.  */
        IM,

        /** Chip Authentication Mapping.  */
        CAM
    }

    /**
     * Returns the PACE protocol object identifier.
     * 
     * @return the PACE protocol object identifier
     */
    override val objectIdentifier: String?

    /**
     * Returns the version.
     * 
     * @return the version
     */
    val version: Int

    /**
     * Returns the parameter identifier.
     * 
     * @return the parameter identifier
     */
    val parameterId: BigInteger?

    /**
     * Constructs a PACE info object.
     * 
     * @param oid the object identifier, indicating what PACE variant
     * is to be used (agreement protocol, mapping type, and secure channel properties)
     * @param version a version number, which should be 2
     * @param parameterId either a standardized domain parameter id from table 6 or a proprietary domain parameter
     */
    constructor(oid: String?, version: Int, parameterId: Int) : this(
        oid,
        version,
        BigInteger.valueOf(parameterId.toLong())
    )

    /**
     * Creates a PACE info object.
     * 
     * @param oid the object identifier, indicating what PACE variant
     * is to be used (agreement protocol, mapping type, and secure channel properties)
     * @param version a version number, which should be 2
     * @param parameterId either a standardized domain parameter id from table 6 or a proprietary domain parameter
     */
    init {
        require(checkRequiredIdentifier(oid)) { "Invalid OID" }
        if (version != VERSION_2) {
            LOGGER.warning("Invalid version, must be 2")
        }
        this.objectIdentifier = oid
        this.version = version
        this.parameterId = parameterId
    }

    override val protocolOIDString: String?
        /**
         * Returns the protocol object identifier as a human readable string.
         * 
         * @return a string describing the PACE protocol object identifier
         */
        get() = toProtocolOIDString(this.objectIdentifier)

    @get:Deprecated("this method will be removed from visible interface (because of dependency on BC API)")
    override val dERObject: ASN1Primitive
        /**
         * Returns a DER object with this SecurityInfo data (DER sequence).
         * 
         * @return a DER object with this SecurityInfo data
         * 
         */
        get() {
            val vector = ASN1EncodableVector()

            /* Protocol */
            vector.add(ASN1ObjectIdentifier(this.objectIdentifier))

            /* Required data */
            vector.add(ASN1Integer(version.toLong()))

            /* Optional data */
            if (parameterId != null) {
                vector.add(ASN1Integer(parameterId))
            }
            return DLSequence(vector)
        }

    override fun toString(): String {
        val result = StringBuilder()
        result.append("PACEInfo [")
        result.append("protocol: ").append(toProtocolOIDString(this.objectIdentifier))
        result.append(", version: ").append(version)
        if (parameterId != null) {
            result.append(", parameterId: ").append(toStandardizedParamIdString(parameterId))
        }
        result.append("]")
        return result.toString()
    }

    override fun hashCode(): Int {
        return (1234567891
                + 7 * objectIdentifier.hashCode() + 5 * version + 3 * (parameterId?.hashCode() ?: 1991))
    }

    override fun equals(other: Any?): Boolean {
        if (other == null) {
            return false
        }
        if (other === this) {
            return true
        }
        if (PACEInfo::class.java != other.javaClass) {
            return false
        }

        val otherPACEInfo = other as PACEInfo

        if (this.objectIdentifier == null && otherPACEInfo.objectIdentifier != null) {
            return false
        }
        if (this.objectIdentifier != null && this.objectIdentifier != otherPACEInfo.objectIdentifier) {
            return false
        }

        if (version != otherPACEInfo.version) {
            return false
        }

        if (parameterId == null && otherPACEInfo.parameterId != null) {
            return false
        }
        if (parameterId != null && parameterId != otherPACEInfo.parameterId) {
            return false
        }

        return true
    }

    /**
     * Returns an ASN1 name for the given object identifier.
     * 
     * @param oid a PACE protocol object identifier
     * 
     * @return an ASN1 name if known, or the original object identifier if not
     */
    private fun toProtocolOIDString(oid: String?): String? {
        if (ID_PACE_DH_GM_3DES_CBC_CBC == oid) {
            return "id-PACE-DH-GM-3DES-CBC-CBC"
        }
        if (ID_PACE_DH_GM_AES_CBC_CMAC_128 == oid) {
            return "id-PACE-DH-GM-AES-CBC-CMAC-128"
        }
        if (ID_PACE_DH_GM_AES_CBC_CMAC_192 == oid) {
            return "id-PACE-DH-GM-AES-CBC-CMAC-192"
        }
        if (ID_PACE_DH_GM_AES_CBC_CMAC_256 == oid) {
            return "id-PACE-DH-GM-AES-CBC-CMAC-256"
        }
        if (ID_PACE_DH_IM_3DES_CBC_CBC == oid) {
            return "id-PACE-DH-IM-3DES-CBC-CBC"
        }
        if (ID_PACE_DH_IM_AES_CBC_CMAC_128 == oid) {
            return "id-PACE-DH-IM-AES-CBC-CMAC-128"
        }
        if (ID_PACE_DH_IM_AES_CBC_CMAC_192 == oid) {
            return "id-PACE-DH-IM-AES-CBC-CMAC-192"
        }
        if (ID_PACE_DH_IM_AES_CBC_CMAC_256 == oid) {
            return "id-PACE-DH-IM-AES-CBC-CMAC-256"
        }
        if (ID_PACE_ECDH_GM_3DES_CBC_CBC == oid) {
            return "id-PACE-ECDH-GM-3DES-CBC-CBC"
        }
        if (ID_PACE_ECDH_GM_AES_CBC_CMAC_128 == oid) {
            return "id-PACE-ECDH-GM-AES-CBC-CMAC-128"
        }
        if (ID_PACE_ECDH_GM_AES_CBC_CMAC_192 == oid) {
            return "id-PACE-ECDH-GM-AES-CBC-CMAC-192"
        }
        if (ID_PACE_ECDH_GM_AES_CBC_CMAC_256 == oid) {
            return "id-PACE-ECDH-GM-AES-CBC-CMAC-256"
        }
        if (ID_PACE_ECDH_IM_3DES_CBC_CBC == oid) {
            return "id-PACE-ECDH-IM-3DES-CBC-CBC"
        }
        if (ID_PACE_ECDH_IM_AES_CBC_CMAC_128 == oid) {
            return "id-PACE-ECDH-IM-AES-CBC-CMAC-128"
        }
        if (ID_PACE_ECDH_IM_AES_CBC_CMAC_192 == oid) {
            return "id-PACE-ECDH-IM-AES-CBC-CMAC-192"
        }
        if (ID_PACE_ECDH_IM_AES_CBC_CMAC_256 == oid) {
            return "id-PACE-ECDH-IM-AES-CBC-CMAC-256"
        }
        if (ID_PACE_ECDH_CAM_AES_CBC_CMAC_128 == oid) {
            return "id-PACE-ECDH-CAM-AES-CBC-CMAC-128"
        }
        if (ID_PACE_ECDH_CAM_AES_CBC_CMAC_192 == oid) {
            return "id-PACE-ECDH-CAM-AES-CBC-CMAC-192"
        }
        if (ID_PACE_ECDH_CAM_AES_CBC_CMAC_256 == oid) {
            return "id-PACE-ECDH-CAM-AES-CBC-CMAC-256"
        }

        return oid
    }

    companion object {
        private const val serialVersionUID = 7960925013249578359L

        private val LOGGER: Logger = Logger.getLogger("org.jmrtd.lds")

        private const val VERSION_2 = 2

        /** Standardized domain parameters. Based on Table 6.  */
        const val PARAM_ID_GFP_1024_160: Int = 0

        /** Standardized domain parameters. Based on Table 6.  */
        const val PARAM_ID_GFP_2048_224: Int = 1

        /** Standardized domain parameters. Based on Table 6.  */
        const val PARAM_ID_GFP_2048_256: Int = 2

        /* RFU 3 - 7 */
        /** Standardized domain parameters. Based on Table 6.  */
        const val PARAM_ID_ECP_NIST_P192_R1: Int = 8

        /** Standardized domain parameters. Based on Table 6.  */
        const val PARAM_ID_ECP_BRAINPOOL_P192_R1: Int = 9

        /** Standardized domain parameters. Based on Table 6.  */
        const val PARAM_ID_ECP_NIST_P224_R1: Int = 10

        /** Standardized domain parameters. Based on Table 6.  */
        const val PARAM_ID_ECP_BRAINPOOL_P224_R1: Int = 11

        /** Standardized domain parameters. Based on Table 6.  */
        const val PARAM_ID_ECP_NIST_P256_R1: Int = 12

        /** Standardized domain parameters. Based on Table 6.  */
        const val PARAM_ID_ECP_BRAINPOOL_P256_R1: Int = 13

        /** Standardized domain parameters. Based on Table 6.  */
        const val PARAM_ID_ECP_BRAINPOOL_P320_R1: Int = 14

        /** Standardized domain parameters. Based on Table 6.  */
        const val PARAM_ID_ECP_NIST_P384_R1: Int = 15

        /** Standardized domain parameters. Based on Table 6.  */
        const val PARAM_ID_ECP_BRAINPOOL_P384_R1: Int = 16

        /** Standardized domain parameters. Based on Table 6.  */
        const val PARAM_ID_ECP_BRAINPOOL_P512_R1: Int = 17

        /** Standardized domain parameters. Based on Table 6.  */
        const val PARAM_ID_ECP_NIST_P521_R1: Int = 18

        /* RFU 19-31 */
        private val PARAMS_GFP_1024_160: DHParameterSpec = Util.toExplicitDHParameterSpec(Util.RFC5114_1024_160)
        private val PARAMS_GFP_2048_224: DHParameterSpec = Util.toExplicitDHParameterSpec(Util.RFC5114_2048_224)
        private val PARAMS_GFP_2048_256: DHParameterSpec = Util.toExplicitDHParameterSpec(Util.RFC5114_2048_256)

        private val PARAMS_ECP_NIST_P192_R1: ECParameterSpec? =
            Util.toExplicitECParameterSpec(ECNamedCurveTable.getParameterSpec("secp192r1"))
        private val PARAMS_ECP_NIST_P224_R1: ECParameterSpec? =
            Util.toExplicitECParameterSpec(ECNamedCurveTable.getParameterSpec("secp224r1"))
        private val PARAMS_ECP_NIST_P256_R1: ECParameterSpec? =
            Util.toExplicitECParameterSpec(ECNamedCurveTable.getParameterSpec("secp256r1"))
        private val PARAMS_ECP_NIST_P384_R1: ECParameterSpec? =
            Util.toExplicitECParameterSpec(ECNamedCurveTable.getParameterSpec("secp384r1"))
        private val PARAMS_ECP_NIST_P521_R1: ECParameterSpec? =
            Util.toExplicitECParameterSpec(ECNamedCurveTable.getParameterSpec("secp521r1"))
        private val PARAMS_ECP_BRAINPOOL_P192_R1: ECParameterSpec? =
            Util.toExplicitECParameterSpec(ECNamedCurveTable.getParameterSpec("brainpoolp192r1"))
        private val PARAMS_ECP_BRAINPOOL_P224_R1: ECParameterSpec? =
            Util.toExplicitECParameterSpec(ECNamedCurveTable.getParameterSpec("brainpoolp224r1"))
        private val PARAMS_ECP_BRAINPOOL_P256_R1: ECParameterSpec? =
            Util.toExplicitECParameterSpec(ECNamedCurveTable.getParameterSpec("brainpoolp256r1"))
        private val PARAMS_ECP_BRAINPOOL_P320_R1: ECParameterSpec? =
            Util.toExplicitECParameterSpec(ECNamedCurveTable.getParameterSpec("brainpoolp320r1"))
        private val PARAMS_ECP_BRAINPOOL_P384_R1: ECParameterSpec? =
            Util.toExplicitECParameterSpec(ECNamedCurveTable.getParameterSpec("brainpoolp384r1"))
        private val PARAMS_ECP_BRAINPOOL_P512_R1: ECParameterSpec? =
            Util.toExplicitECParameterSpec(ECNamedCurveTable.getParameterSpec("brainpoolp512r1"))

        private val ALLOWED_REQUIRED_IDENTIFIERS: MutableSet<String?> = TreeSet<String?>(
            listOf<String?>(
                *arrayOf<String>(
                    ID_PACE_DH_GM_3DES_CBC_CBC,
                    ID_PACE_DH_GM_AES_CBC_CMAC_128,
                    ID_PACE_DH_GM_AES_CBC_CMAC_192,
                    ID_PACE_DH_GM_AES_CBC_CMAC_256,
                    ID_PACE_DH_IM_3DES_CBC_CBC,
                    ID_PACE_DH_IM_AES_CBC_CMAC_128,
                    ID_PACE_DH_IM_AES_CBC_CMAC_192,
                    ID_PACE_DH_IM_AES_CBC_CMAC_256,
                    ID_PACE_ECDH_GM_3DES_CBC_CBC,
                    ID_PACE_ECDH_GM_AES_CBC_CMAC_128,
                    ID_PACE_ECDH_GM_AES_CBC_CMAC_192,
                    ID_PACE_ECDH_GM_AES_CBC_CMAC_256,
                    ID_PACE_ECDH_IM_3DES_CBC_CBC,
                    ID_PACE_ECDH_IM_AES_CBC_CMAC_128,
                    ID_PACE_ECDH_IM_AES_CBC_CMAC_192,
                    ID_PACE_ECDH_IM_AES_CBC_CMAC_256,
                    ID_PACE_ECDH_CAM_AES_CBC_CMAC_128,
                    ID_PACE_ECDH_CAM_AES_CBC_CMAC_192,
                    ID_PACE_ECDH_CAM_AES_CBC_CMAC_256
                )
            )
        )

        /**
         * Creates a PACE info from an encoding.
         * 
         * @param paceInfoBytes the encoded bytes
         * 
         * @return a PACE info object
         */
        fun createPACEInfo(paceInfoBytes: ByteArray?): PACEInfo {
            /*
     * FIXME: Should add a constructor to PACEInfo that takes byte[] or InputStream, or
     * align this with SecurityInfo.getInstance().
     */
            val sequence = ASN1Sequence.getInstance(paceInfoBytes)
            val oid = (sequence.getObjectAt(0) as ASN1ObjectIdentifier).getId()
            val requiredData = sequence.getObjectAt(1).toASN1Primitive()
            var optionalData: ASN1Primitive? = null
            if (sequence.size() == 3) {
                optionalData = sequence.getObjectAt(2).toASN1Primitive()
            }

            val version = (requiredData as ASN1Integer).value.toInt()
            var parameterId: BigInteger? = null
            if (optionalData != null) {
                parameterId = (optionalData as ASN1Integer).value
            }

            return PACEInfo(oid, version, parameterId)
        }

        /**
         * Checks whether the object identifier is valid for describing a PACE protocol.
         * 
         * @param oid a PACE object identifier
         * 
         * @return a boolean indicating whether the object identifier describes a known PACE protocol
         */
        fun checkRequiredIdentifier(oid: String?): Boolean {
            return ALLOWED_REQUIRED_IDENTIFIERS.contains(oid)
        }

        /*
   * FIXME: perhaps we should introduce an enum for PACE identifiers (with a String toOID() method),
   * so that we can get rid of static methods below. -- MO
   */
        /**
         * Returns the mapping type for a given PACE protocol object identifier.
         * 
         * @param oid a PACE protocol object identifier
         * 
         * @return the mapping type
         */
        fun toMappingType(oid: String?): MappingType {
            if (ID_PACE_DH_GM_3DES_CBC_CBC == oid
                || ID_PACE_DH_GM_AES_CBC_CMAC_128 == oid
                || ID_PACE_DH_GM_AES_CBC_CMAC_192 == oid
                || ID_PACE_DH_GM_AES_CBC_CMAC_256 == oid
                || ID_PACE_ECDH_GM_3DES_CBC_CBC == oid
                || ID_PACE_ECDH_GM_AES_CBC_CMAC_128 == oid
                || ID_PACE_ECDH_GM_AES_CBC_CMAC_192 == oid
                || ID_PACE_ECDH_GM_AES_CBC_CMAC_256 == oid
            ) {
                return MappingType.GM
            } else if (ID_PACE_DH_IM_3DES_CBC_CBC == oid
                || ID_PACE_DH_IM_AES_CBC_CMAC_128 == oid
                || ID_PACE_DH_IM_AES_CBC_CMAC_192 == oid
                || ID_PACE_DH_IM_AES_CBC_CMAC_256 == oid
                || ID_PACE_ECDH_IM_3DES_CBC_CBC == oid
                || ID_PACE_ECDH_IM_AES_CBC_CMAC_128 == oid
                || ID_PACE_ECDH_IM_AES_CBC_CMAC_192 == oid
                || ID_PACE_ECDH_IM_AES_CBC_CMAC_256 == oid
            ) {
                return MappingType.IM
            } else if (ID_PACE_ECDH_CAM_AES_CBC_CMAC_128 == oid
                || ID_PACE_ECDH_CAM_AES_CBC_CMAC_192 == oid
                || ID_PACE_ECDH_CAM_AES_CBC_CMAC_256 == oid
            ) {
                return MappingType.CAM
            }

            throw NumberFormatException("Unknown OID: \"$oid\"")
        }

        /**
         * Returns the key agreement algorithm (`"DH"` or `"ECDH"`)
         * for a PACE protocol object identifier.
         * 
         * @param oid a PACE protocol object identifier
         * 
         * @return a key agreement algorithm as JCE mnemonic string
         */
        fun toKeyAgreementAlgorithm(oid: String?): String {
            if (ID_PACE_DH_GM_3DES_CBC_CBC == oid
                || ID_PACE_DH_GM_AES_CBC_CMAC_128 == oid
                || ID_PACE_DH_GM_AES_CBC_CMAC_192 == oid
                || ID_PACE_DH_GM_AES_CBC_CMAC_256 == oid
                || ID_PACE_DH_IM_3DES_CBC_CBC == oid
                || ID_PACE_DH_IM_AES_CBC_CMAC_128 == oid
                || ID_PACE_DH_IM_AES_CBC_CMAC_192 == oid
                || ID_PACE_DH_IM_AES_CBC_CMAC_256 == oid
            ) {
                return "DH"
            } else if (ID_PACE_ECDH_GM_3DES_CBC_CBC == oid
                || ID_PACE_ECDH_GM_AES_CBC_CMAC_128 == oid
                || ID_PACE_ECDH_GM_AES_CBC_CMAC_192 == oid
                || ID_PACE_ECDH_GM_AES_CBC_CMAC_256 == oid
                || ID_PACE_ECDH_IM_3DES_CBC_CBC == oid
                || ID_PACE_ECDH_IM_AES_CBC_CMAC_128 == oid
                || ID_PACE_ECDH_IM_AES_CBC_CMAC_192 == oid
                || ID_PACE_ECDH_IM_AES_CBC_CMAC_256 == oid
                || ID_PACE_ECDH_CAM_AES_CBC_CMAC_128 == oid
                || ID_PACE_ECDH_CAM_AES_CBC_CMAC_192 == oid
                || ID_PACE_ECDH_CAM_AES_CBC_CMAC_256 == oid
            ) {
                return "ECDH"
            }

            throw NumberFormatException("Unknown OID: \"$oid\"")
        }

        /**
         * Returns the encryption algorithm described in the PACE protocol object identifier.
         * 
         * @param oid the PACE protocol object identifier
         * 
         * @return a encryption algorithm as JCE mnemonic string
         */
        fun toCipherAlgorithm(oid: String?): String {
            if (ID_PACE_DH_GM_3DES_CBC_CBC == oid
                || ID_PACE_DH_IM_3DES_CBC_CBC == oid
                || ID_PACE_ECDH_GM_3DES_CBC_CBC == oid
                || ID_PACE_ECDH_IM_3DES_CBC_CBC == oid
            ) {
                return "DESede"
            } else if (ID_PACE_DH_GM_AES_CBC_CMAC_128 == oid
                || ID_PACE_DH_GM_AES_CBC_CMAC_192 == oid
                || ID_PACE_DH_GM_AES_CBC_CMAC_256 == oid
                || ID_PACE_DH_IM_AES_CBC_CMAC_128 == oid
                || ID_PACE_DH_IM_AES_CBC_CMAC_192 == oid
                || ID_PACE_DH_IM_AES_CBC_CMAC_256 == oid
                || ID_PACE_ECDH_GM_AES_CBC_CMAC_128 == oid
                || ID_PACE_ECDH_GM_AES_CBC_CMAC_192 == oid
                || ID_PACE_ECDH_GM_AES_CBC_CMAC_256 == oid
                || ID_PACE_ECDH_IM_AES_CBC_CMAC_128 == oid
                || ID_PACE_ECDH_IM_AES_CBC_CMAC_192 == oid
                || ID_PACE_ECDH_IM_AES_CBC_CMAC_256 == oid
                || ID_PACE_ECDH_CAM_AES_CBC_CMAC_128 == oid
                || ID_PACE_ECDH_CAM_AES_CBC_CMAC_192 == oid
                || ID_PACE_ECDH_CAM_AES_CBC_CMAC_256 == oid
            ) {
                return "AES"
            }

            throw NumberFormatException("Unknown OID: \"$oid\"")
        }

        /**
         * Returns the digest algorithm described in the PACE protocol object identifier.
         * 
         * @param oid the PACE protocol object identifier
         * 
         * @return a digest algorithm as JCE mnemonic string
         */
        fun toDigestAlgorithm(oid: String?): String {
            if (ID_PACE_DH_GM_3DES_CBC_CBC == oid
                || ID_PACE_DH_IM_3DES_CBC_CBC == oid
                || ID_PACE_ECDH_GM_3DES_CBC_CBC == oid
                || ID_PACE_ECDH_IM_3DES_CBC_CBC == oid
                || ID_PACE_DH_GM_AES_CBC_CMAC_128 == oid
                || ID_PACE_DH_IM_AES_CBC_CMAC_128 == oid
                || ID_PACE_ECDH_GM_AES_CBC_CMAC_128 == oid
                || ID_PACE_ECDH_IM_AES_CBC_CMAC_128 == oid
                || ID_PACE_ECDH_CAM_AES_CBC_CMAC_128 == oid
            ) {
                return "SHA-1"
            } else if (ID_PACE_DH_GM_AES_CBC_CMAC_192 == oid
                || ID_PACE_DH_IM_AES_CBC_CMAC_192 == oid
                || ID_PACE_ECDH_GM_AES_CBC_CMAC_192 == oid
                || ID_PACE_ECDH_IM_AES_CBC_CMAC_192 == oid
                || ID_PACE_ECDH_CAM_AES_CBC_CMAC_192 == oid
                || ID_PACE_DH_GM_AES_CBC_CMAC_256 == oid
                || ID_PACE_DH_IM_AES_CBC_CMAC_256 == oid
                || ID_PACE_ECDH_GM_AES_CBC_CMAC_256 == oid
                || ID_PACE_ECDH_IM_AES_CBC_CMAC_256 == oid
                || ID_PACE_ECDH_CAM_AES_CBC_CMAC_256 == oid
            ) {
                return "SHA-256"
            }

            throw NumberFormatException("Unknown OID: \"$oid\"")
        }

        /**
         * Returns the key length (128, 192, or 256) described in the given PACE protocol object identifier.
         * 
         * @param oid a PACE protocol object identifier
         * 
         * @return the key length in bits
         */
        fun toKeyLength(oid: String?): Int {
            if (ID_PACE_DH_GM_3DES_CBC_CBC == oid
                || ID_PACE_DH_IM_3DES_CBC_CBC == oid
                || ID_PACE_ECDH_GM_3DES_CBC_CBC == oid
                || ID_PACE_ECDH_IM_3DES_CBC_CBC == oid
                || ID_PACE_DH_GM_AES_CBC_CMAC_128 == oid
                || ID_PACE_DH_IM_AES_CBC_CMAC_128 == oid
                || ID_PACE_ECDH_GM_AES_CBC_CMAC_128 == oid
                || ID_PACE_ECDH_IM_AES_CBC_CMAC_128 == oid
                || ID_PACE_ECDH_CAM_AES_CBC_CMAC_128 == oid
            ) {
                return 128
            } else if (ID_PACE_DH_GM_AES_CBC_CMAC_192 == oid
                || ID_PACE_ECDH_GM_AES_CBC_CMAC_192 == oid
                || ID_PACE_DH_IM_AES_CBC_CMAC_192 == oid
                || ID_PACE_ECDH_IM_AES_CBC_CMAC_192 == oid
                || ID_PACE_ECDH_CAM_AES_CBC_CMAC_192 == oid
            ) {
                return 192
            } else if (ID_PACE_DH_GM_AES_CBC_CMAC_256 == oid
                || ID_PACE_DH_IM_AES_CBC_CMAC_256 == oid
                || ID_PACE_ECDH_GM_AES_CBC_CMAC_256 == oid
                || ID_PACE_ECDH_IM_AES_CBC_CMAC_256 == oid
                || ID_PACE_ECDH_CAM_AES_CBC_CMAC_256 == oid
            ) {
                return 256
            }

            throw NumberFormatException("Unknown OID: \"$oid\"")
        }

        /**
         * Derives a JCE algorithm parameter specification from a PACE standard domain parameter integer.
         * 
         * @param stdDomainParam the standard domain parameter
         * 
         * @return a JCE algorithm parameter specification
         */
        fun toParameterSpec(stdDomainParam: BigInteger): AlgorithmParameterSpec? {
            return toParameterSpec(stdDomainParam.toInt())
        }

        /**
         * Derives a JCE algorithm parameter specification from a PACE standard domain parameter integer.
         * 
         * @param stdDomainParam the standard domain parameter
         * 
         * @return a JCE algorithm parameter specification
         */
        fun toParameterSpec(stdDomainParam: Int): AlgorithmParameterSpec? {
            when (stdDomainParam) {
                PARAM_ID_GFP_1024_160 -> return PARAMS_GFP_1024_160
                PARAM_ID_GFP_2048_224 -> return PARAMS_GFP_2048_224
                PARAM_ID_GFP_2048_256 -> return PARAMS_GFP_2048_256
                PARAM_ID_ECP_NIST_P192_R1 -> return PARAMS_ECP_NIST_P192_R1
                PARAM_ID_ECP_BRAINPOOL_P192_R1 -> return PARAMS_ECP_BRAINPOOL_P192_R1
                PARAM_ID_ECP_NIST_P224_R1 -> return PARAMS_ECP_NIST_P224_R1
                PARAM_ID_ECP_BRAINPOOL_P224_R1 -> return PARAMS_ECP_BRAINPOOL_P224_R1
                PARAM_ID_ECP_NIST_P256_R1 -> return PARAMS_ECP_NIST_P256_R1
                PARAM_ID_ECP_BRAINPOOL_P256_R1 -> return PARAMS_ECP_BRAINPOOL_P256_R1
                PARAM_ID_ECP_BRAINPOOL_P320_R1 -> return PARAMS_ECP_BRAINPOOL_P320_R1
                PARAM_ID_ECP_NIST_P384_R1 -> return PARAMS_ECP_NIST_P384_R1
                PARAM_ID_ECP_BRAINPOOL_P384_R1 -> return PARAMS_ECP_BRAINPOOL_P384_R1
                PARAM_ID_ECP_BRAINPOOL_P512_R1 -> return PARAMS_ECP_BRAINPOOL_P512_R1
                PARAM_ID_ECP_NIST_P521_R1 -> return PARAMS_ECP_NIST_P521_R1
                else -> throw NumberFormatException("Unknown standardized domain parameters $stdDomainParam")
            }
        }

        /**
         * Derives a human readable algorithm description from a PACE standard domain parameter integer.
         * 
         * @param stdDomainParam the standard domain parameter
         * 
         * @return a human readable algorithm description
         */
        fun toStandardizedParamIdString(stdDomainParam: BigInteger?): String? {
            if (stdDomainParam == null) {
                return "null"
            }

            when (stdDomainParam.toInt()) {
                PARAM_ID_GFP_1024_160 -> return "1024-bit MODP Group with 160-bit Prime Order Subgroup"
                PARAM_ID_GFP_2048_224 -> return "2048-bit MODP Group with 224-bit Prime Order Subgroup"
                PARAM_ID_GFP_2048_256 -> return "2048-bit MODP Group with 256-bit Prime Order Subgroup"
                PARAM_ID_ECP_NIST_P192_R1 -> return "NIST P-192 (secp192r1)"
                PARAM_ID_ECP_BRAINPOOL_P192_R1 -> return "BrainpoolP192r1"
                PARAM_ID_ECP_NIST_P224_R1 -> return "NIST P-224 (secp224r1)"
                PARAM_ID_ECP_BRAINPOOL_P224_R1 -> return "BrainpoolP224r1"
                PARAM_ID_ECP_NIST_P256_R1 -> return "NIST P-256 (secp256r1)"
                PARAM_ID_ECP_BRAINPOOL_P256_R1 -> return "BrainpoolP256r1"
                PARAM_ID_ECP_BRAINPOOL_P320_R1 -> return "BrainpoolP320r1"
                PARAM_ID_ECP_NIST_P384_R1 -> return "NIST P-384 (secp384r1)"
                PARAM_ID_ECP_BRAINPOOL_P384_R1 -> return "BrainpoolP384r1"
                PARAM_ID_ECP_BRAINPOOL_P512_R1 -> return "BrainpoolP512r1"
                PARAM_ID_ECP_NIST_P521_R1 -> return "NIST P-521 (secp521r1)"
                else -> return stdDomainParam.toString()
            }
        }
    }
}
