/*
 * JMRTD - A Java API for accessing machine readable travel documents.
 *
 * Copyright (C) 2006 - 2018  The JMRTD team
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 *
 * $Id: PACEResult.java 1763 2018-02-18 07:41:30Z martijno $
 */
/*
 * Modified work Copyright (C) 2026 Alessandro Giaquinto
 * Kotlin port of JMRTD
 *
 * Licensed under LGPL 3.0
 */
package org.jmrtd.protocol

import org.jmrtd.AccessKeySpec
import org.jmrtd.Util
import org.jmrtd.lds.PACEInfo
import java.io.Serializable
import java.security.KeyPair
import java.security.PublicKey

/**
 * Result of PACE protocol.
 * 
 * @author The JMRTD team (info@jmrtd.org)
 * 
 * @version $Revision: 1763 $
 */
open class PACEResult
/**
 * The result of a PACE protocol run.
 * 
 * @param pACEKey the access key
 * @param mappingType the mapping type, `GM`, `IM`, or `CAM`
 * @param agreementAlg the agreement algorithm, `"DH"` or `"ECDH"`
 * @param cipherAlg the cipher algorithm
 * @param digestAlg the digest algorithm
 * @param keyLength the key length
 * @param mappingResult the result of the mapping step
 * @param pCDKeyPair the key pair generated by the PCD
 * @param pICCPublicKey the public key sent by the PICC
 * @param wrapper the resulting secure messaging wrapper
 */(
  /**
     * Returns the access key that was used.
     * 
     * @return the PACE key
     */
    val pACEKey: AccessKeySpec,
  /**
     * Returns the mapping type.
     * 
     * @return the mapping type
     */
  val mappingType: PACEInfo.MappingType,
  /**
     * Returns the agreement algorithm that was used in the PACE protocol run.
     * 
     * @return the agreement algorithm that was used in the PACE protocol run
     */
  val agreementAlg: String,
  /**
     * Returns the cipher algorithm that was reported in the PACE info.
     * 
     * @return the cipher algorithm
     */
  val cipherAlg: String,
  /**
     * Returns the digest algorithm that was reported in the PACE info.
     * 
     * @return the digest algorithm
     */
  val digestAlg: String,
  /**
     * Returns the key length that was reported in the PACE info.
     * 
     * @return the key length
     */
  val keyLength: Int,
  /**
     * Returns the mapping result.
     * 
     * @return the mapping result
     */
  val mappingResult: PACEMappingResult,
  /**
     * Returns the ephemeral key pair that was generated by the terminal.
     * 
     * @return the ephemeral key pair that was generated by the terminal
     */
    val pCDKeyPair: KeyPair,
  /**
     * Returns the public key that was sent by the ICC (the chip).
     * 
     * @return the public key that was sent by the ICC
     */
    val pICCPublicKey: PublicKey,
  /**
     * Returns the secure messaging wrapper that was created after completion of the PACE protocol run.
     * 
     * @return the secure messaging wrapper that was created after completion of the PACE protocol run
     */
  val wrapper: SecureMessagingWrapper
) : Serializable {
    /**
     * Returns a textual representation of this PACE result.
     * 
     * @return a textual representation of this PACE result
     */
    override fun toString(): String = buildString {
        append("PACEResult [")
        append("paceKey: ").append(pACEKey)
        append(", mappingType: ").append(mappingType)
        append(", agreementAlg: ").append(agreementAlg)
        append(", cipherAlg: ").append(cipherAlg)
        append(", digestAlg: ").append(digestAlg)
        append(", keyLength: ").append(keyLength)
        append(", mappingResult: ").append(mappingResult)
        append(", piccPublicKey: ").append(Util.getDetailedPublicKeyAlgorithm(pICCPublicKey))
        append(", pcdPrivateKey: ").append(Util.getDetailedPrivateKeyAlgorithm(pCDKeyPair.private))
        append(", pcdPublicKey: ").append(Util.getDetailedPublicKeyAlgorithm(pCDKeyPair.public))
        append(']')
    }

    override fun hashCode(): Int {
        val prime = 1991
        var result = 11
        result = prime * result + pACEKey.hashCode()
        result = prime * result + agreementAlg.hashCode()
        result = prime * result + cipherAlg.hashCode()
        result = prime * result + digestAlg.hashCode()
        result = prime * result + mappingResult.hashCode()
        result = prime * result + keyLength
        result = prime * result + mappingType.hashCode()
        result = prime * result + pCDKeyPair.hashCode()
        result = prime * result + pICCPublicKey.hashCode()
        result = prime * result + wrapper.hashCode()
        return result
    }

    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is PACEResult) return false

        return pACEKey == other.pACEKey
                && agreementAlg == other.agreementAlg
                && cipherAlg == other.cipherAlg
                && digestAlg == other.digestAlg
                && keyLength == other.keyLength
                && mappingType == other.mappingType
                && mappingResult == other.mappingResult
                && pCDKeyPair == other.pCDKeyPair
                && pICCPublicKey == other.pICCPublicKey
                && wrapper == other.wrapper
    }

    companion object {
        private const val serialVersionUID = -6819675856205885052L
    }
}
