/*
 * JMRTD - A Java API for accessing machine readable travel documents.
 *
 * Copyright (C) 2006 - 2018  The JMRTD team
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 *
 * $Id: PACEGMMappingResult.java 1763 2018-02-18 07:41:30Z martijno $
 */
/*
 * Modified work Copyright (C) 2026 Alessandro Giaquinto
 * Kotlin port of JMRTD
 *
 * Licensed under LGPL 3.0
 */
package kmrtd.protocol

import java.security.KeyPair
import java.security.PublicKey
import java.security.spec.AlgorithmParameterSpec

/**
 * The result of the PACE nonce mapping step in Generic Mapping setting.
 * 
 * @author The JMRTD team (info@jmrtd.org)
 * @version $Revision: $
 */
abstract class PACEGMMappingResult(
    staticParameters: AlgorithmParameterSpec?, piccNonce: ByteArray?,
    piccMappingPublicKey: PublicKey, pcdMappingKeyPair: KeyPair,
    ephemeralParameters: AlgorithmParameterSpec
) : PACEMappingResult(staticParameters, piccNonce, ephemeralParameters) {
    /**
     * Returns the public key that was sent by the PICC.
     * 
     * @return the PICC's public key
     */
    val pICCMappingPublicKey: PublicKey = piccMappingPublicKey

    /**
     * Returns the key-pair generated by the PCD.
     * 
     * @return the PCD's key-pair
     */
    val pCDMappingKeyPair: KeyPair = pcdMappingKeyPair

    override fun hashCode(): Int {
        val prime = 31
        var result = super.hashCode()
        result =
            prime * result + (if (this.pICCMappingPublicKey == null) 0 else pICCMappingPublicKey.hashCode())
        return result
    }

    override fun equals(obj: Any?): Boolean {
        if (this === obj) {
            return true
        }
        if (!super.equals(obj)) {
            return false
        }
        if (javaClass != obj?.javaClass) {
            return false
        }

        val other = obj as PACEGMMappingResult
        if (this.pICCMappingPublicKey != other.pICCMappingPublicKey) {
            return false
        }

        if (this.pCDMappingKeyPair != other.pCDMappingKeyPair) {
            return false
        }

        return true
    }
}
