/*
 * JMRTD - A Java API for accessing machine readable travel documents.
 *
 * Copyright (C) 2006 - 2018  The JMRTD team
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 *
 * $Id: PACECAMResult.java 1763 2018-02-18 07:41:30Z martijno $
 */
/*
 * Modified work Copyright (C) 2026 Alessandro Giaquinto
 * Kotlin port of JMRTD
 *
 * Licensed under LGPL 3.0
 */
package kmrtd.protocol

import net.sf.scuba.util.Hex
import kmrtd.AccessKeySpec
import kmrtd.lds.PACEInfo.MappingType
import java.security.KeyPair
import java.security.PublicKey

/**
 * The result of a PACE-CAM protocol execution.
 * 
 * @author The JMRTD team (info@jmrtd.org)
 * 
 * @version $Revision: $
 */
class PACECAMResult(
    paceKey: AccessKeySpec?,
    agreementAlg: String?, cipherAlg: String?, digestAlg: String?, keyLength: Int,
    mappingResult: PACEMappingResult?,
    pcdKeyPair: KeyPair?, piccPublicKey: PublicKey?,
    encryptedChipAuthenticationData: ByteArray?,
    chipAuthenticationData: ByteArray?,
    wrapper: SecureMessagingWrapper?
) : PACEResult(
    paceKey,
    MappingType.CAM,
    agreementAlg,
    cipherAlg,
    digestAlg,
    keyLength,
    mappingResult,
    pcdKeyPair,
    piccPublicKey,
    wrapper
) {
    private var encryptedChipAuthenticationData: ByteArray? = null

    private var chipAuthenticationData: ByteArray?

    /**
     * Constructs a result.
     * 
     * @param paceKey the static PACE key (derived from MRZ, CAN, PIN, or PUK)
     * @param agreementAlg the agreement algorithm that was used
     * @param cipherAlg the cipher algorithm that was used
     * @param digestAlg the digest algorithm that was used
     * @param keyLength the key length that was used
     * @param mappingResult the result from the mapping step
     * @param pcdKeyPair the key-pair generated by the PCD
     * @param piccPublicKey the public key sent by the chip
     * @param encryptedChipAuthenticationData the encrypted Chip Authentication data sent by the PICC
     * @param chipAuthenticationData the decrypted Chip Authentication data
     * @param wrapper the secure messaging wrapper that resulted
     */
    init {
        if (encryptedChipAuthenticationData != null) {
            this.encryptedChipAuthenticationData = ByteArray(encryptedChipAuthenticationData.size)
            System.arraycopy(
                encryptedChipAuthenticationData,
                0,
                this.encryptedChipAuthenticationData,
                0,
                encryptedChipAuthenticationData.size
            )
        }

        this.chipAuthenticationData = null
        if (chipAuthenticationData != null) {
            this.chipAuthenticationData = ByteArray(chipAuthenticationData.size)
            System.arraycopy(chipAuthenticationData, 0, this.chipAuthenticationData, 0, chipAuthenticationData.size)
        }
    }

    /**
     * Returns the encrypted Chip Authentication data.
     * 
     * @return the encrypted Chip Authentication data
     */
    fun getEncryptedChipAuthenticationData(): ByteArray? {
        val data = encryptedChipAuthenticationData ?: return null
        /*if (encryptedChipAuthenticationData == null) {
            return null
        }

        val result = ByteArray(encryptedChipAuthenticationData?.size)*/
        //System.arraycopy(encryptedChipAuthenticationData, 0, result, 0, encryptedChipAuthenticationData?.size)
        //return result
        return data.copyOf()
    }

    /**
     * Returns the result of decrypting the encrypted Chip Authentication data.
     * 
     * @return the decrypted Chip Authentication data
     */
    fun getChipAuthenticationData(): ByteArray? {
        val data = chipAuthenticationData ?: return null
        /*if (chipAuthenticationData == null) {
            return null
        }

        val result = ByteArray(chipAuthenticationData?.size)
        System.arraycopy(chipAuthenticationData, 0, result, 0, chipAuthenticationData?.size)
        return result*/
        return data.copyOf()
    }

    public override fun hashCode(): Int {
        val prime = 31
        var result = super.hashCode()
        result = prime * result + chipAuthenticationData.contentHashCode()
        result = prime * result + encryptedChipAuthenticationData.contentHashCode()
        return result
    }

    public override fun equals(obj: Any?): Boolean {
        if (this === obj) {
            return true
        }
        if (!super.equals(obj)) {
            return false
        }
        if (javaClass != obj?.javaClass) {
            return false
        }

        val other = obj as PACECAMResult
        return chipAuthenticationData.contentEquals(other.chipAuthenticationData) && encryptedChipAuthenticationData.contentEquals(
            other.encryptedChipAuthenticationData
        )
    }

    public override fun toString(): String = buildString {
            append("PACECAMResult [")
            append("paceKey: $pACEKey, ")
            append("mappingType: $mappingType, ")
            append("agreementAlg: $agreementAlg, ")
            append("cipherAlg: $cipherAlg, ")
            append("digestAlg: $digestAlg, ")
            append("keyLength: $keyLength, ")
            append("mappingResult: $mappingResult, ")
            append("pcdKeyPair: $pCDKeyPair, ")
            append("piccPublicKey: $pICCPublicKey, ")
            append("encryptedChipAuthenticationData: ${Hex.bytesToHexString(encryptedChipAuthenticationData)}, ")
            append("wrapper: $wrapper, ")
            append("chipAuthenticationData: ${Hex.bytesToHexString(chipAuthenticationData)}]")

    }

    companion object {
        private val serialVersionUID = -4288710920347109329L
    }
}
