/*
 * JMRTD - A Java API for accessing machine readable travel documents.
 *
 * Copyright (C) 2006 - 2018  The JMRTD team
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 *
 * $Id: PACEResult.java 1763 2018-02-18 07:41:30Z martijno $
 */
/*
 * Modified work Copyright (C) 2026 Alessandro Giaquinto
 * Kotlin port of JMRTD
 *
 * Licensed under LGPL 3.0
 */
package kmrtd.protocol

import kmrtd.AccessKeySpec
import kmrtd.Util
import kmrtd.lds.PACEInfo
import java.io.Serializable
import java.security.KeyPair
import java.security.PublicKey

/**
 * Result of PACE protocol.
 * 
 * @author The JMRTD team (info@jmrtd.org)
 * @version $Revision: 1763 $
 */
open class PACEResult
/**
 * The result of a PACE protocol run.
 * 
 * @param pACEKey       the access key
 * @param mappingType   the mapping type, `GM`, `IM`, or `CAM`
 * @param agreementAlg  the agreement algorithm, `"DH"` or `"ECDH"`
 * @param cipherAlg     the cipher algorithm
 * @param digestAlg     the digest algorithm
 * @param keyLength     the key length
 * @param mappingResult the result of the mapping step
 * @param pCDKeyPair    the key pair generated by the PCD
 * @param pICCPublicKey the public key sent by the PICC
 * @param wrapper       the resulting secure messaging wrapper
 */(
    /**
     * Returns the access key that was used.
     * 
     * @return the PACE key
     */
    val pACEKey: AccessKeySpec?,
    /**
     * Returns the mapping type.
     * 
     * @return the mapping type
     */
    val mappingType: PACEInfo.MappingType?,
    /**
     * Returns the agreement algorithm that was used in the PACE protocol run.
     * 
     * @return the agreement algorithm that was used in the PACE protocol run
     */
    val agreementAlg: String?,
    /**
     * Returns the cipher algorithm that was reported in the PACE info.
     * 
     * @return the cipher algorithm
     */
    val cipherAlg: String?,
    /**
     * Returns the digest algorithm that was reported in the PACE info.
     * 
     * @return the digest algorithm
     */
    val digestAlg: String?,
    /**
     * Returns the key length that was reported in the PACE info.
     * 
     * @return the key length
     */
    val keyLength: Int,
    /**
     * Returns the mapping result.
     * 
     * @return the mapping result
     */
    val mappingResult: PACEMappingResult?,
    /**
     * Returns the ephemeral key pair that was generated by the terminal.
     * 
     * @return the ephemeral key pair that was generated by the terminal
     */
    val pCDKeyPair: KeyPair?,
    /**
     * Returns the public key that was sent by the ICC (the chip).
     * 
     * @return the public key that was sent by the ICC
     */
    val pICCPublicKey: PublicKey?,
    /**
     * Returns the secure messaging wrapper that was created after completion of the PACE protocol run.
     * 
     * @return the secure messaging wrapper that was created after completion of the PACE protocol run
     */
    val wrapper: SecureMessagingWrapper?
) : Serializable {
    /**
     * Returns a textual representation of this PACE result.
     * 
     * @return a textual representation of this PACE result
     */
    override fun toString(): String {
        return StringBuilder()
            .append("PACEResult [")
            .append("paceKey: ").append(this.pACEKey)
            .append(", mappingType: ").append(mappingType)
            .append(", agreementAlg: $agreementAlg")
            .append(", cipherAlg: $cipherAlg")
            .append(", digestAlg: $digestAlg")
            .append(", keyLength: $keyLength")
            .append(", mappingResult: $mappingResult")
            .append(", piccPublicKey: " + Util.getDetailedPublicKeyAlgorithm(this.pICCPublicKey))
            .append(", pcdPrivateKey: " + Util.getDetailedPrivateKeyAlgorithm(pCDKeyPair!!.private))
            .append(", pcdPublicKey: " + Util.getDetailedPublicKeyAlgorithm(pCDKeyPair.public))
            .toString()
    }

    override fun hashCode(): Int {
        val prime = 1991
        var result = 11
        result = prime * result + (if (this.pACEKey == null) 0 else pACEKey.hashCode())
        result = prime * result + (agreementAlg?.hashCode() ?: 0)
        result = prime * result + (cipherAlg?.hashCode() ?: 0)
        result = prime * result + (digestAlg?.hashCode() ?: 0)
        result = prime * result + (mappingResult?.hashCode() ?: 0)
        result = prime * result + keyLength
        result = prime * result + (mappingType?.hashCode() ?: 0)
        result = prime * result + (if (this.pCDKeyPair == null) 0 else pCDKeyPair.hashCode())
        result = prime * result + (if (this.pICCPublicKey == null) 0 else pICCPublicKey.hashCode())
        result = prime * result + (wrapper?.hashCode() ?: 0)
        return result
    }

    override fun equals(obj: Any?): Boolean {
        if (this === obj) {
            return true
        }
        if (obj == null) {
            return false
        }
        if (javaClass != obj.javaClass) {
            return false
        }

        val other = obj as PACEResult
        if (this.pACEKey == null) {
            if (other.pACEKey != null) {
                return false
            }
        } else if (this.pACEKey != other.pACEKey) {
            return false
        }
        if (agreementAlg == null) {
            if (other.agreementAlg != null) {
                return false
            }
        } else if (agreementAlg != other.agreementAlg) {
            return false
        }
        if (cipherAlg == null) {
            if (other.cipherAlg != null) {
                return false
            }
        } else if (cipherAlg != other.cipherAlg) {
            return false
        }
        if (digestAlg == null) {
            if (other.digestAlg != null) {
                return false
            }
        } else if (digestAlg != other.digestAlg) {
            return false
        }
        if (mappingResult == null) {
            if (other.mappingResult != null) {
                return false
            }
        } else if (mappingResult != other.mappingResult) {
            return false
        }
        if (keyLength != other.keyLength) {
            return false
        }
        if (mappingType != other.mappingType) {
            return false
        }
        if (this.pCDKeyPair == null) {
            if (other.pCDKeyPair != null) {
                return false
            }
        } else if (this.pCDKeyPair != other.pCDKeyPair) {
            return false
        }
        if (this.pICCPublicKey == null) {
            if (other.pICCPublicKey != null) {
                return false
            }
        } else if (this.pICCPublicKey != other.pICCPublicKey) {
            return false
        }
        if (wrapper == null) {
            if (other.wrapper != null) {
                return false
            }
        } else if (wrapper != other.wrapper) {
            return false
        }

        return true
    }
}
